name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Build
        shell: pwsh
        run: $output = dotnet build Source/GraphicSetter/GraphicSetter/GraphicSetter.csproj --configuration Release --nologo --verbosity quiet /clp:ErrorsOnly 2>&1; $exitCode = $LASTEXITCODE; $output | Select-String -Pattern ': error '; exit $exitCode
